apiVersion: apps/v1
kind: Deployment
metadata:
  name: nextjs
  #namespace: frontend
spec:
  selector:
    matchLabels:
      app: nextjs # has to match .spec.template.metadata.labels
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: nextjs # has to match .spec.selector.matchLabels
    spec:
      containers:
      - name: nextjs
        image: nextjs:v1
        imagePullPolicy: Never
        # resources:
        #   requests:
        #     cpu: 100m
        #     memory: 100Mi
        #   limits:
        #     cpu: 100m
        #     memory: 100Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        ports:
        - name: nextjs
          containerPort: 3000
      restartPolicy: Always