apiVersion: v1
kind: Service
metadata:
  name: nextjs
  #namespace: default
spec:
  selector:
    app: nextjs
  type: ClusterIP
  clusterIP: None
  sessionAffinity: None
  sessionAffinityConfig:
    clientIP:
      timeoutSeconds: 10800
  ports:
  - name: nextjs
    protocol: TCP
    port: 3000
    #targetPort: 3000 